# Annex A: Profiles and levels # {#annex_a:_profiles_and_levels}

## General ## {#general}

Profiles and levels specify restrictions on the capabilities needed to decode
the bitstreams.

The profile specifies the bit depth and subsampling formats supported, while the
level defines resolution and performance characteristics.

## Profiles ## {#profiles}

There are three named profiles:
 * "Main" compliant decoders must be able to decode streams with seq_profile equal to 0.
 * "High" compliant decoders must be able to decode streams with seq_profile less than or equal to 1.
 * "Professional" compliant decoders must be able to decode streams with seq_profile less than or equal to 2.

Note: The Main profile supports YUV 4:2:0 or monochrome bitstreams with bit
depth equal to 8 or 10. The High profile further adds support for 4:4:4
bitstreams with the same bit depth constraints. Finally, the Professional
profile extends support over the High profile to also bitstreams with bit depth
equal to 12, and also adds support for the 4:2:2 video format.


## Levels ## {#levels}

Each operating point contains a syntax element seq_level_idx.

The following table defines the mapping from the syntax element (which takes
integer values) to the defined levels:

<table class="table table-sm table-bordered">
    <thead>
      <tr>
        <th>Value of seq_level_idx</th>
        <th>Level</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0</td>
        <td>2.0</td>
      </tr>
      <tr>
        <td>1</td>
        <td>2.1</td>
      </tr>
      <tr>
        <td>2</td>
        <td>2.2</td>
      </tr>
      <tr>
        <td>3</td>
        <td>2.3</td>
      </tr>
      <tr>
        <td>4</td>
        <td>3.0</td>
      </tr>
      <tr>
        <td>5</td>
        <td>3.1</td>
      </tr>
      <tr>
        <td>6</td>
        <td>3.2</td>
      </tr>
      <tr>
        <td>7</td>
        <td>3.3</td>
      </tr>
      <tr>
        <td>8</td>
        <td>4.0</td>
      </tr>
      <tr>
        <td>9</td>
        <td>4.1</td>
      </tr>
      <tr>
        <td>10</td>
        <td>4.2</td>
      </tr>
      <tr>
        <td>11</td>
        <td>4.3</td>
      </tr>
      <tr>
        <td>12</td>
        <td>5.0</td>
      </tr>
      <tr>
        <td>13</td>
        <td>5.1</td>
      </tr>
      <tr>
        <td>14</td>
        <td>5.2</td>
      </tr>
      <tr>
        <td>15</td>
        <td>5.3</td>
      </tr>
      <tr>
        <td>16</td>
        <td>6.0</td>
      </tr>
      <tr>
        <td>17</td>
        <td>6.1</td>
      </tr>
      <tr>
        <td>18</td>
        <td>6.2</td>
      </tr>
      <tr>
        <td>19</td>
        <td>6.3</td>
      </tr>
      <tr>
        <td>20</td>
        <td>7.0</td>
      </tr>
      <tr>
        <td>21</td>
        <td>7.1</td>
      </tr>
      <tr>
        <td>22</td>
        <td>7.2</td>
      </tr>
      <tr>
        <td>23</td>
        <td>7.3</td>
      </tr>
      <tr>
        <td>24-30</td>
        <td>Reserved</td>
      </tr>
      <tr>
        <td>31</td>
        <td>Maximum parameters</td>
      </tr>
    </tbody>
  </table>


Note: The level uses a X.Y format.
X is equal to `2 + (seq_level_idx >> 2)`.
Y is given by `(seq_level_idx & 3)`.


The level defines variables as specified in the following tables:

<table class="table table-sm table-bordered">
    <thead>
      <tr>
        <th>Level</th>
        <th>MaxPicSize</th>
        <th>MaxHSize</th>
        <th>MaxVSize</th>
        <th>MaxDisplayRate</th>
        <th>MaxDecodeRate</th>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <th>(Samples)</th>
        <th>(Samples)</th>
        <th>(Samples)</th>
        <th>(Samples/sec)</th>
        <th>(Samples/sec)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>2.0</td>
        <td>147456</td>
        <td>2048</td>
        <td>1152</td>
        <td>4,423,680</td>
        <td>5,529,600</td>
      </tr>
      <tr>
        <td>2.1</td>
        <td>278784</td>
        <td>2816</td>
        <td>1584</td>
        <td>8,363,520</td>
        <td>10,454,400</td>
      </tr>
      <tr>
        <td>3.0</td>
        <td>665856</td>
        <td>4352</td>
        <td>2448</td>
        <td>19,975,680</td>
        <td>24,969,600</td>
      </tr>
      <tr>
        <td>3.1</td>
        <td>1065024</td>
        <td>5504</td>
        <td>3096</td>
        <td>31,950,720</td>
        <td>39,938,400</td>
      </tr>
      <tr>
        <td>4.0</td>
        <td>2359296</td>
        <td>6144</td>
        <td>3456</td>
        <td>70,778,880</td>
        <td>77,856,768</td>
      </tr>
      <tr>
        <td>4.1</td>
        <td>2359296</td>
        <td>6144</td>
        <td>3456</td>
        <td>141,557,760</td>
        <td>155,713,536</td>
      </tr>
      <tr>
        <td>5.0</td>
        <td>8912896</td>
        <td>8192</td>
        <td>4352</td>
        <td>267,386,880</td>
        <td>273,715,200</td>
      </tr>
      <tr>
        <td>5.1</td>
        <td>8912896</td>
        <td>8192</td>
        <td>4352</td>
        <td>534,773,760</td>
        <td>547,430,400</td>
      </tr>
      <tr>
        <td>5.2</td>
        <td>8912896</td>
        <td>8192</td>
        <td>4352</td>
        <td>1,069,547,520</td>
        <td>1,094,860,800</td>
      </tr>
      <tr>
        <td>5.3</td>
        <td>8912896</td>
        <td>8192</td>
        <td>4352</td>
        <td>1,069,547,520</td>
        <td>1,176,502,272</td>
      </tr>
      <tr>
        <td>6.0</td>
        <td>35651584</td>
        <td>16384</td>
        <td>8704</td>
        <td>1,069,547,520</td>
        <td>1,176,502,272</td>
      </tr>
      <tr>
        <td>6.1</td>
        <td>35651584</td>
        <td>16384</td>
        <td>8704</td>
        <td>2,139,095,040</td>
        <td>2,189,721,600</td>
      </tr>
      <tr>
        <td>6.2</td>
        <td>35651584</td>
        <td>16384</td>
        <td>8704</td>
        <td>4,278,190,080</td>
        <td>4,379,443,200</td>
      </tr>
      <tr>
        <td>6.3</td>
        <td>35651584</td>
        <td>16384</td>
        <td>8704</td>
        <td>4,278,190,080</td>
        <td>4,706,009,088</td>
      </tr>
    </tbody>
  </table>

Note: The missing entries in these tables (for example level 2.2 and 7.0) represent
levels that are not yet defined.

<table class="table table-sm table-bordered">
    <thead>
      <tr>
        <th>Level</th>
        <th>MaxHeaderRate</th>
        <th>MainMbps</th>
        <th>HighMbps</th>
        <th>MainCR</th>
        <th>HighCR</th>
        <th>MaxTiles</th>
        <th>MaxTileCols</th>
        <th>Example</th>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <th>(/sec)</th>
        <th>(MBits/sec)</th>
        <th>(MBits/sec)</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>2.0</td>
        <td>150</td>
        <td>1.5</td>
        <td>-</td>
        <td>2</td>
        <td>-</td>
        <td>8</td>
        <td>4</td>
        <td>426x240@30fps</td>
      </tr>
      <tr>
        <td>2.1</td>
        <td>150</td>
        <td>3.0</td>
        <td>-</td>
        <td>2</td>
        <td>-</td>
        <td>8</td>
        <td>4</td>
        <td>640x360@30fps</td>
      </tr>
      <tr>
        <td>3.0</td>
        <td>150</td>
        <td>6.0</td>
        <td>-</td>
        <td>2</td>
        <td>-</td>
        <td>16</td>
        <td>6</td>
        <td>854x480@30fps</td>
      </tr>
      <tr>
        <td>3.1</td>
        <td>150</td>
        <td>10.0</td>
        <td>-</td>
        <td>2</td>
        <td>-</td>
        <td>16</td>
        <td>6</td>
        <td>1280x720@30fps</td>
      </tr>
      <tr>
        <td>4.0</td>
        <td>300</td>
        <td>12.0</td>
        <td>30.0</td>
        <td>4</td>
        <td>4</td>
        <td>32</td>
        <td>8</td>
        <td>1920x1080@30fps</td>
      </tr>
      <tr>
        <td>4.1</td>
        <td>300</td>
        <td>20.0</td>
        <td>50.0</td>
        <td>4</td>
        <td>4</td>
        <td>32</td>
        <td>8</td>
        <td>1920x1080@60fps</td>
      </tr>
      <tr>
        <td>5.0</td>
        <td>300</td>
        <td>30.0</td>
        <td>100.0</td>
        <td>6</td>
        <td>4</td>
        <td>64</td>
        <td>8</td>
        <td>3840x2160@30fps</td>
      </tr>
      <tr>
        <td>5.1</td>
        <td>300</td>
        <td>40.0</td>
        <td>160.0</td>
        <td>8</td>
        <td>4</td>
        <td>64</td>
        <td>8</td>
        <td>3840x2160@60fps</td>
      </tr>
      <tr>
        <td>5.2</td>
        <td>300</td>
        <td>60.0</td>
        <td>240.0</td>
        <td>8</td>
        <td>4</td>
        <td>64</td>
        <td>8</td>
        <td>3840x2160@120fps</td>
      </tr>
      <tr>
        <td>5.3</td>
        <td>300</td>
        <td>60.0</td>
        <td>240.0</td>
        <td>8</td>
        <td>4</td>
        <td>64</td>
        <td>8</td>
        <td>3840x2160@120fps</td>
      </tr>
      <tr>
        <td>6.0</td>
        <td>300</td>
        <td>60.0</td>
        <td>240.0</td>
        <td>8</td>
        <td>4</td>
        <td>128</td>
        <td>16</td>
        <td>7680x4320@30fps</td>
      </tr>
      <tr>
        <td>6.1</td>
        <td>300</td>
        <td>100.0</td>
        <td>480.0</td>
        <td>8</td>
        <td>4</td>
        <td>128</td>
        <td>16</td>
        <td>7680x4320@60fps</td>
      </tr>
      <tr>
        <td>6.2</td>
        <td>300</td>
        <td>160.0</td>
        <td>800.0</td>
        <td>8</td>
        <td>4</td>
        <td>128</td>
        <td>16</td>
        <td>7680x4320@120fps</td>
      </tr>
      <tr>
        <td>6.3</td>
        <td>300</td>
        <td>160.0</td>
        <td>800.0</td>
        <td>8</td>
        <td>4</td>
        <td>128</td>
        <td>16</td>
        <td>7680x4320@120fps</td>
      </tr>
    </tbody>
  </table>


Note: Examples are given for non-scalable cases, but the constraints also
apply to each operating point of a scalable stream.  For example, consider a
60fps spatial scalable stream with a base layer at 960x540, and an enhancement
layer at 1920x1080. The operating point containing just the base layer may be
labelled as level 3.0, while the operating point containing both the base and
enhancement layer may be labelled as level 4.1.


Note: HighMbps and HighCR values are not defined for levels below level 4.0.
seq_tier equal to 1 can only be signaled for level 4.0 and above.


The bitstream constraints depend on the variables in the table, and additional variables derived as follows:

 * TileWidth is defined as (MiColEnd - MiColStart) * MI_SIZE
 * TileHeight is defined as (MiRowEnd - MiRowStart) * MI_SIZE
 * RightMostTile is defined as MiColEnd == MiCols
 * CroppedTileWidth is defined as FrameWidth - MiColStart * MI_SIZE
 * CroppedTileHeight is defined as FrameHeight - MiRowStart * MI_SIZE
 * MaxTileSizeInLumaSamples is defined as the largest product of TileWidth * TileHeight for all tiles within the coded video sequence
 * showCount for a particular frame is defined as the number of times the frame is shown (either due to show_frame equal to 1, or via the show_existing_frame mechanism)
 * TotalDisplayLumaSampleRate is defined as the sum of the UpscaledWidth * FrameHeight * showCount of all frames that belong to the temporal unit that belongs to the operating point, divided by the time difference between the display time of the first frame of the current temporal unit and the display time of the first frame of the next temporal unit (if present). For the last temporal unit in the bitstream, the time difference from the previous temporal unit is used. In particular, for spatial and quality scalability, this limit applies to output pictures that belong to this particular layer. For temporal scalability, this restriction applies to the output pictures that belong to the indicated scalability layer and to the layers below.
 * TotalDecodedLumaSampleRate is defined as the sum of the UpscaledWidth * FrameHeight of all frames with show_existing_frame equal to 0 that belong to the temporal unit that belongs to the operating point, divided by the time difference between the decoding time of the first frame of the current temporal unit and the decoding time of the first frame of the next temporal unit (if present). For the last temporal unit in the bitstream, the time difference from the previous temporal unit is used.
 * NumFrameHeadersSec is defined as the number of OBU_FRAME and OBU_FRAME_HEADER OBUs received per second (this number does not include duplicate frame headers or frame headers with show_existing_frame equal to 1)
 * CompressedSize is defined for each frame as the total bytes in the OBUs related to this frame (OBU_FRAME, OBU_FRAME_HEADER, OBU_METADATA, OBU_TILE_GROUP), minus 128 (to allow for overhead of metadata and header data)
 * If seq_profile is equal to 0, PicSizeProfileFactor is set equal to 15, else if seq_profile is equal to 1, PicSizeProfileFactor is set equal to 30, otherwise PicSizeProfileFactor is set equal to 36
 * UnCompressedSize is defined for each frame as ( UpscaledWidth * FrameHeight * PicSizeProfileFactor ) >> 3
 * SpeedAdj is defined as TotalDecodedLumaSampleRate ÷ MaxDisplayRate
 * If seq_tier is equal to 0, MinCompBasis is set equal to MainCR, otherwise MinCompBasis is set equal to HighCR
 * If still_picture is equal to 0, MinPicCompressRatio is set equal to Max( 0.8, MinCompBasis * SpeedAdj ), otherwise MinPicCompressRatio is set equal to 0.8
 * CompressedRatio is defined as UnCompressedSize ÷ CompressedSize

Note: The ÷ operator represents standard mathematical division (in contrast to the / operator which represents integer division).


If scalability_mode_idc is not present or equal to a reserved value, then
TemporalParallelNum and TemporalParallelDen are defined to be equal to 1.

Otherwise, if scalability_mode_idc is not equal to SCALABILITY_SS,
TemporalParallelDen is defined as 1 and TemporalParallelNum is defined as
`(1 << ( TemporalLayers - 1 ))` where TemporalLayers is the number of temporal
layers as defined in the semantics for scalability_mode_idc.

Otherwise (scalability_mode_idc is equal to SCALABILITY_SS),
TemporalParallelNum and TemporalParallelDen are defined as follows:

~~~~~ c
NumIndependent = 0
for ( i = 0; i < temporal_group_size; i++ ) {
  if ( temporal_group_temporal_id[ i ] ) {
    independent = 1
    for ( j = 0; j < temporal_group_ref_cnt[ i ]; j++ ) {
      ref = (i - temporal_group_ref_pic_diff[ i ][ j ] + temporal_group_size) % temporal_group_size
      if ( temporal_group_temporal_id[ ref ] == temporal_group_temporal_id[ i ] )
        independent = 0
    }
    NumIndependent += independent
  }
}
TemporalParallelNum = temporal_group_size
TemporalParallelDen = temporal_group_size - NumIndependent
~~~~~

When the mapped level is contained in the tables above, it is a requirement of bitstream conformance that the following constraints hold:

 * UpscaledWidth * FrameHeight is less than or equal to MaxPicSize
 * UpscaledWidth is less than or equal to MaxHSize
 * FrameHeight is less than or equal to MaxVSize
 * TotalDisplayLumaSampleRate is less than or equal to MaxDisplayRate
 * TotalDecodedLumaSampleRate is less than or equal to MaxDecodeRate
 * NumFrameHeadersSec is less than or equal to MaxHeaderRate
 * The number of tiles per second is less than or equal to MaxTiles * 120
 * NumTiles is less than or equal to MaxTiles
 * TileCols is less than or equal to MaxTileCols
 * CompressedRatio is greater than or equal to MinPicCompressRatio
 * ( TileWidth * SuperresDenom / SUPERRES_NUM ) is less than or equal to MAX_TILE_WIDTH for each tile
 * For each tile, if use_superres is equal to 0 and RightMostTile is equal to 0, then TileWidth is greater than or equal to 64
 * For each tile, if use_superres is equal to 1 and RightMostTile is equal to 0, then TileWidth is greater than or equal to 128
 * TileWidth * TileHeight is less than or equal to 4096 * 2304 for each tile
 * FrameWidth is greater than or equal to 16
 * FrameHeight is greater than or equal to 16
 * CroppedTileWidth is greater than or equal to 8 for each tile
 * CroppedTileHeight is greater than or equal to 8 for each tile
 * MaxTileSizeInLumaSamples * NumFrameHeadersSec * TemporalParallelDen/TemporalParallelNum is less than or equal to 588,251,136 (where this number is the decode luma sample rate of 4096x2176 * 60fps * 1.1)

  Note: The purpose of this constraint is to ensure that for decode luma
  sample rates above 4K60 there is sufficient parallelism for decoder
  implementations. Parallelism can be chosen by the encoder as either tile
  level parallelism or temporal layer parallelism or a combination provided the
  above constraint holds. The constraint has no effect on levels 5.1 and below.
  

If seq_level_idx is equal to 31 (indicating the maximum parameters level), then
there are no level-based constraints on the bitstream.

Note: The maximum parameters level should only be set for bitstreams that do
not conform to any other level. Typically this would be used for large
resolution still images.


The buffer model is used to define additional conformance requirements.

These requirements depend on the following level, tier, and profile dependent variables:

 * If seq_tier is equal to 0, MaxBitrate is equal to MainMbps multiplied by 1,000,000
 * Otherwise (seq_tier is equal to 1), MaxBitrate is equal to HighMbps multiplied by 1,000,000
 * MaxBufferSize is equal to MaxBitrate multiplied by 1 second
 * If seq_profile is equal to 0, BitrateProfileFactor is equal to 1.0
 * If seq_profile is equal to 1, BitrateProfileFactor is equal to 2.0
 * If seq_profile is equal to 2, BitrateProfileFactor is equal to 3.0

## Decoder Conformance ## {#decoder_conformance}

A level X.Y compliant decoder must be able to decode all bitstreams (that can be
decoded by the general decoding process) that conform to that level.

When doing that, the decoder must be able to display output frames according to
the display schedule if such is indicated by the bitstream.

Note: If the level of a bitstream is equal to 31 (indicating the maximum
parameters level), the decoder should examine the properties of the bitstream
and decide whether to decode it or not. There is no assurance that all pictures
will be decoded. A decoder would typically decode pictures up to a certain
maximum uncompressed picture size (or maximum compressed picture size or maximum
width or maximum tile size) that the decoder maker considers sufficiently
extreme for their use case, and not decode anything bigger than that.


A level X.Y compliant decoder should be able to decode tile list OBUs (via the
large scale tile decoding process) at a rate of 180 tile list OBUs per second
subject to the following level-dependent constraints:

 * UpscaledWidth * FrameHeight is less than or equal to MaxPicSize
 * UpscaledWidth is less than or equal to MaxHSize
 * FrameHeight is less than or equal to MaxVSize
 * TileWidth * TileHeight * ( tile_count_minus_1 + 1 ) * 180 is less than or equal to ( MaxDecodeRate / 2 )
 * For each tile list OBU, BytesPerTileList * 8 * 180 is less than or equal to MaxBitrate

Where BytesPerTileList is defined as the sum of (coded_tile_data_size_minus_1 + 1) for each tile list entry in the tile list OBU.
